export const PROJECT_FETCH_PENDING = "PROJECTLIST/FETCH/PENDING";
export const PROJECT_FETCH_FUFILLED = "PROJECTLIST/FETCH/FUFILLED";
export const PROJECT_FETCH_REJECTED = "PROJECTLIST/FETCH/REJECTED";
