export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const EDIT_TASK = "EDIT_TASK";
export const GET_TASK_TYPE = "GET_TASK_TYPE";
export const GET_TASK_PRIORITY = "GET_TASK_PRIORITY";
export const GET_TASK_STATUS = "GET_TASK_STATUS";
